Repository intel/confidential-cloud-native-primitives, pull requests merged in 2023-07, with the labels that each got.

#31 .github/pr-check-rust.yaml: Add Rust code scan in CI
  .github/workflows/pr-check-rust.yaml
Labels: ci/cd

#32 .github/pr-pylint.yaml: Add Python scan in Github action CI.
  .github/pylintrc
  .github/workflows/pr-pylint.yaml
  sdk/python3/ccnp/requirements.txt
Labels: ci/cd

#30 .github/pr-golanglint.yaml: Add Golong lint for CI
  .github/workflows/pr-golanglint.yaml
Labels: ci/cd

#35 CI/CD: add action for container build
  .github/workflows/pr-container-check.yaml
  .github/workflows/pr-license-python.yaml
Labels: ci/cd

#42 README.md: Add Notes at the bottom of README
  README.md
Labels: documentation

#44 workflows/pr-check-rust.yaml: update lib install step due to build error
  .github/workflows/pr-check-rust.yaml
Labels: ci/cd

#43 CI/CD: further restrict github actions
  .github/workflows/pr-golanglint.yaml
  .github/workflows/pr-pylint.yaml
Labels: ci/cd

#34 service/eventlog-server: add Dockerfile
  container/build.sh
  container/eventlog-server/Dockerfile
Labels: feature

#46 CI/CD: fix golanglint
  .github/workflows/pr-golanglint.yaml
Labels: bug, ci/cd

#47 fix: fix golang lint error
  .github/workflows/pr-golanglint.yaml
Labels: bug, ci/cd

#41 workflows: update to use github hosted runner
  .github/workflows/pr-container-check.yaml
  .github/workflows/pr-license-python.yaml
Labels: ci/cd

#38 api: add api definitions for the services
  api/eventlog-server.proto
  api/measurement-server.proto
  api/quote-server.proto
Labels: feature

#68 README.md: Add current github workflow status badges
  README.md
Labels: documentation, enhancement

#33 service/quote-server: add TDX support for quote fetching
  service/quote-server/Cargo.toml
  service/quote-server/Makefile
  service/quote-server/build.rs
  service/quote-server/deny.toml
  service/quote-server/deployment/quote_server-daemonset.yaml
  service/quote-server/proto/quote_server.proto
  service/quote-server/src/quote_server.rs
  service/quote-server/src/tee.rs
Labels: feature

#27 service/eventlog-server: add base logic
  service/eventlog-server/Makefile
  service/eventlog-server/go.mod
  service/eventlog-server/go.sum
  service/eventlog-server/proto/eventlog-server.pb.go
  service/eventlog-server/proto/eventlog-server.proto
  service/eventlog-server/proto/eventlog-server_grpc.pb.go
  service/eventlog-server/server/server.go
Labels: feature

#28 service/eventlog-server: add TDX support for eventlog fetching
  service/eventlog-server/resources/tdx.go
  service/eventlog-server/server/server.go
Labels: feature

#29 service/eventlog-server: add placeholder for tpm option
  service/eventlog-server/resources/tpm.go
  service/eventlog-server/server/server.go
Labels: feature

#39 service/measurement-server: add skeleton for measurement-server service
  service/measurement-server/Makefile
  service/measurement-server/go.mod
  service/measurement-server/go.sum
  service/measurement-server/proto/measurement-server.pb.go
  service/measurement-server/proto/measurement-server.proto
  service/measurement-server/proto/measurement-server_grpc.pb.go
  service/measurement-server/server/server.go
Labels: feature

#40 service/quote-server: add Dockerfile
  container/quote-server/Dockerfile
Labels: feature

#48 service/measurement-server: add tdx support
  service/measurement-server/resources/base.go
  service/measurement-server/resources/tdx.go
  service/measurement-server/server/server.go
Labels: feature

#50 service/measurement-server: add Dockerfile for the service
  container/measurement-server/Dockerfile
Labels: feature

#54 device-plugin/ccnp-device-plugin: device plugin for CCNP
  device-plugin/ccnp-device-plugin/Makefile
  device-plugin/ccnp-device-plugin/cmd/server/app.go
  device-plugin/ccnp-device-plugin/container/Dockerfile
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/Chart.yaml
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/_helpers.tpl
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/cluster-role-binding.yaml
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/daemonset.yaml
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/serviceaccount.yaml
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/values.yaml
  device-plugin/ccnp-device-plugin/deploy/node-feature-rules.yaml
  device-plugin/ccnp-device-plugin/go.mod
  device-plugin/ccnp-device-plugin/go.sum
  device-plugin/ccnp-device-plugin/pkg/server/server.go
Labels: feature

#49 service/measurement-server: add placeholder for other kinds of measurements
  service/measurement-server/resources/base.go
  service/measurement-server/resources/sev.go
  service/measurement-server/resources/tdx.go
  service/measurement-server/resources/tpm.go
  service/measurement-server/server/server.go
Labels: feature

#51 service/eventlog-server: add helm chart
  chart/eventlog-server/Chart.yaml
  chart/eventlog-server/templates/NOTES.txt
  chart/eventlog-server/templates/_helpers.tpl
  chart/eventlog-server/templates/daemonset.yaml
  chart/eventlog-server/templates/namespace.yaml
  chart/eventlog-server/templates/serviceaccount.yaml
  chart/eventlog-server/values.yaml
Labels: feature

#52 service/measurement-server: add helm chart
  deployment/charts/measurement-server/Chart.yaml
  deployment/charts/measurement-server/templates/NOTES.txt
  deployment/charts/measurement-server/templates/_helpers.tpl
  deployment/charts/measurement-server/templates/daemonset.yaml
  deployment/charts/measurement-server/templates/namespace.yaml
  deployment/charts/measurement-server/templates/serviceaccount.yaml
  deployment/charts/measurement-server/values.yaml
  deployment/manifests/measurement-server-deployment.yaml
Labels: feature

#71 fix: change hierarchy for deployment files
  deployment/charts/eventlog-server/Chart.yaml
  deployment/charts/eventlog-server/templates/NOTES.txt
  deployment/charts/eventlog-server/templates/_helpers.tpl
  deployment/charts/eventlog-server/templates/daemonset.yaml
  deployment/charts/eventlog-server/templates/namespace.yaml
  deployment/charts/eventlog-server/templates/serviceaccount.yaml
  deployment/charts/eventlog-server/values.yaml
  deployment/manifests/quote-server-deployment.yaml
Labels: enhancement

#72 deployment: add deployment yaml for eventlog and split namespace
  deployment/manifests/eventlog-server-deployment.yaml
  deployment/manifests/measurement-server-deployment.yaml
  deployment/manifests/namespace.yaml
Labels: enhancement

#76 fix: fix license format and clean up comments
  service/eventlog-server/resources/tdx.go
  service/eventlog-server/resources/tpm.go
  service/eventlog-server/server/server.go
  service/measurement-server/resources/base.go
  service/measurement-server/resources/sev.go
  service/measurement-server/resources/tdx.go
  service/measurement-server/resources/tpm.go
  service/measurement-server/server/server.go
Labels: enhancement

#75 sdk/get-eventlog: add basic logic
  .github/pylintrc
  sdk/python3/ccnp/requirements.txt
  sdk/python3/ccnp/src/eventlog/__init__.py
  sdk/python3/ccnp/src/eventlog/eventlog_sdk.py
  sdk/python3/ccnp/src/eventlog/eventlog_server_pb2.py
  sdk/python3/ccnp/src/eventlog/eventlog_server_pb2.pyi
  sdk/python3/ccnp/src/eventlog/eventlog_server_pb2_grpc.py
Labels: feature

#77 ccnp-device-plugin: add init container to detect TDX version
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/daemonset.yaml
  device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/values.yaml
  device-plugin/ccnp-device-plugin/pkg/server/server.go
Labels: enhancement

#78 add License header according to standard template
  device-plugin/ccnp-device-plugin/cmd/server/app.go
  device-plugin/ccnp-device-plugin/pkg/server/server.go
  service/eventlog-server/Makefile
  service/measurement-server/Makefile
  service/quote-server/Makefile
  service/quote-server/build.rs
  service/quote-server/src/quote_server.rs
  service/quote-server/src/tee.rs
Labels: enhancement

#53 Documentation: add readme file for eventlog-server
  .github/cspell.json
  service/eventlog-server/README.md
Labels: documentation

#66 Documentation: add readme file for quote server
  .github/cspell.json
  service/quote-server/README.md
Labels: documentation

#67 Documentation: add readme file for ccnp-device-plugin
  .github/cspell.json
  device-plugin/ccnp-device-plugin/README.md
Labels: documentation
