Repository intel/confidential-cloud-native-primitives, pull requests merged in 2023-08, with the labels that each got.

#89 deployment: enhance mount for eventlog server
  deployment/charts/eventlog-server/templates/daemonset.yaml
  deployment/charts/eventlog-server/values.yaml
  deployment/manifests/eventlog-server-deployment.yaml
Labels: enhancement

#86 service/quote-server: add more unit tests for quote server
  service/quote-server/Cargo.toml
  service/quote-server/src/quote_server.rs
  service/quote-server/src/tee.rs
Labels: ci/cd

#98 Doc: add readme for ccnp sdk
  sdk/python3/README.md
Labels: documentation
